spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server:8761/eureka/}
