server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: ecommerce
    password: ecommerce
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: order_schema
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    schemas: order_schema
    default-schema: order_schema
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET:dev-secret-must-be-at-least-32-bytes!!}

service:
  internal-token: ${SERVICE_INTERNAL_TOKEN:dev-internal-token-change-me-32b!!}

management:
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
